name: cryphive
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.1.2
  firebase_database: ^10.2.4
  google_fonts: ^5.1.0
  file_picker: ^5.3.0
  provider: ^6.0.5
  http: ^1.1.0
  flutter_bloc: ^7.0.0
  intl: ^0.18.1
  flutter_web_browser: ^0.17.1
  url_launcher: ^6.0.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/cryphive_word.png
    - assets/images/cryphive_word_nobg.png
    - assets/images/cryphive_logo.png
    - assets/images/cryphive_logo_nobg.png
    - assets/images/h_icon.png
    - assets/images/i_icon.png
    - assets/images/v_icon.png
    - assets/images/e_icon.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
